Repository MitchellTFord/discord-bot, pull requests merged in 2021-12, with the labels that each got.

#14 Add some instructions
  README.md
Labels: documentation, good first issue

#10 Add Dependabot, configure for Gradle & GH Actions
  .github/dependabot.yml
Labels: enhancement

#22 Added JaCoCo
  README.md
  build.gradle
Labels: dependencies

#13 Add Feature Request and Bug Report issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#25 Added AssertJ dependency
  build.gradle
Labels: dependencies

#34 Bean for logged gateway discord client
  src/main/java/com/mitchelltford/discordbot/Application.java
  src/main/java/com/mitchelltford/discordbot/GatewayDiscordClientConfig.java
  src/main/resources/application.properties
  src/test/java/com/mitchelltford/discordbot/ApplicationTests.java
Labels: enhancement
