Repository MitchellTFord/discord-bot, pull requests merged in 2022-01, with the labels that each got.

#41 Feature/command handling
  src/main/java/com/mitchelltford/discordbot/Bot.java
Labels: enhancement

#48 Modular Command-Handling (Partially Complete)
  src/main/java/com/mitchelltford/discordbot/Bot.java
  src/main/java/com/mitchelltford/discordbot/Command.java
  src/main/java/com/mitchelltford/discordbot/DefaultCommand.java
  src/main/java/com/mitchelltford/discordbot/GatewayDiscordClientConfig.java
  src/main/java/com/mitchelltford/discordbot/commands/Ping.java
Labels: enhancement, java

#47 added spotless documentation
  build.gradle
  gradle.properties
Labels: documentation

#42 LavaPlayer Basic Functionality
  build.gradle
  src/main/java/com/mitchelltford/discordbot/LavaPlayer.java
  src/main/java/com/mitchelltford/discordbot/LavaPlayerAudioProvider.java
  src/main/java/com/mitchelltford/discordbot/LavaPlayerEventHandler.java
  src/main/java/com/mitchelltford/discordbot/commands/Play.java
  src/main/java/com/mitchelltford/discordbot/commands/Skip.java
  src/main/java/com/mitchelltford/discordbot/commands/Stop.java
Labels: enhancement

#51 :children_crossing: Added support for command descriptions. Also adde…
  src/main/java/com/mitchelltford/discordbot/Command.java
  src/main/java/com/mitchelltford/discordbot/DefaultCommand.java
  src/main/java/com/mitchelltford/discordbot/commands/Help.java
  src/main/java/com/mitchelltford/discordbot/commands/Ping.java
Labels: enhancement
